import { describe, expect, it } from 'vitest';
import { SANITIZER_POLICY } from '@security/sanitizer';

describe('SANITIZER_POLICY', () => {
  it('exposes the complete reviewed tag and URL-attribute policy', () => {
    expect([...SANITIZER_POLICY.allowedTags]).toEqual([
      'p',
      'br',
      'strong',
      'b',
      'em',
      'i',
      'u',
      's',
      'strike',
      'mark',
      'small',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'ul',
      'ol',
      'li',
      'dl',
      'dt',
      'dd',
      'blockquote',
      'code',
      'pre',
      'kbd',
      'samp',
      'var',
      'a',
      'span',
      'div',
      'section',
      'article',
      'aside',
      'header',
      'footer',
      'nav',
      'figure',
      'figcaption',
      'img',
      'picture',
      'source',
      'audio',
      'video',
      'sub',
      'sup',
      'hr',
      'time',
      'abbr',
      'cite',
      'q',
      'table',
      'thead',
      'tbody',
      'tfoot',
      'tr',
      'th',
      'td',
      'caption',
      'colgroup',
      'col',
    ]);
    expect([...SANITIZER_POLICY.removeCompletely]).toEqual([
      'script',
      'style',
      'iframe',
      'object',
      'embed',
      'link',
      'meta',
      'base',
      'form',
      'input',
      'button',
      'select',
      'textarea',
      'svg',
      'math',
      'template',
      'frame',
      'frameset',
      'noframes',
      'noscript',
    ]);
    expect([...SANITIZER_POLICY.globalAttributes]).toEqual([
      'id',
      'class',
      'lang',
      'dir',
      'title',
      'role',
      'tabindex',
    ]);
    expect([...SANITIZER_POLICY.urlAttributes]).toEqual(['href', 'src', 'cite', 'poster']);
  });

  it('exposes the complete reviewed per-tag attribute policy', () => {
    expect(
      Object.fromEntries(
        Object.entries(SANITIZER_POLICY.attributesByTag).map(([tag, attributes]) => [
          tag,
          [...attributes],
        ]),
      ),
    ).toEqual({
      a: ['href', 'target', 'rel', 'download', 'hreflang', 'type'],
      img: ['src', 'srcset', 'sizes', 'alt', 'width', 'height', 'loading', 'decoding'],
      picture: [],
      source: ['src', 'srcset', 'sizes', 'type', 'media'],
      audio: ['src', 'controls', 'autoplay', 'loop', 'muted', 'preload'],
      video: [
        'src',
        'poster',
        'controls',
        'autoplay',
        'loop',
        'muted',
        'preload',
        'width',
        'height',
        'playsinline',
      ],
      time: ['datetime'],
      abbr: ['title'],
      q: ['cite'],
      blockquote: ['cite'],
      table: ['summary'],
      th: ['colspan', 'rowspan', 'scope', 'headers', 'abbr'],
      td: ['colspan', 'rowspan', 'headers'],
      col: ['span'],
      colgroup: ['span'],
      ol: ['start', 'reversed', 'type'],
      li: ['value'],
      code: ['class'],
      pre: ['class'],
    });
  });
});
