/**
 * Render `ExtractedSchema` to a TypeScript source string.
 *
 * The output is one self-contained `.ts` file that ships:
 *
 *   - one `interface` per global and per collection,
 *   - nested `interface` declarations for `group`/`array`/`blocks`,
 *   - discriminated unions for `blocks` fields (one variant per slug),
 *   - `PayloadCollections` / `PayloadGlobals` maps for slug-keyed
 *     access (`PayloadCollections['posts']`), and
 *   - a `PayloadSlug` alias.
 *
 * Nothing in the runtime depends on this output — consumers import
 * what they need by name.
 *
 * @module @codegen/emit/emit-types
 */

import type {
  ExtractedBlock,
  ExtractedField,
  ExtractedSchema,
  ExtractedSlug,
} from '../parser/types';
import { toPascalCase } from '../parser/extract-field';

export interface EmitOptions {
  /** When true, includes a `@deprecated` JSDoc on localized fields. */
  readonly markLocalizedAsDeprecated?: boolean;
  /** Header text injected at the top of the output. Defaults sensibly. */
  readonly header?: string;
}

const DEFAULT_HEADER =
  '// Auto-generated by payload-live-preview/codegen.\n' +
  '// Do not edit by hand — run `pll-codegen` to regenerate.\n' +
  '/* eslint-disable */';

export function emitTypes(schema: ExtractedSchema, options: EmitOptions = {}): string {
  const lines: string[] = [];
  lines.push(options.header ?? DEFAULT_HEADER);
  lines.push('');
  lines.push(
    'import type { PayloadMedia, PayloadRelationship } from "payload-live-preview";',
  );
  lines.push('');

  // Emit slug interfaces (globals + collections), each potentially
  // accompanied by nested interface declarations.
  const seenAuxNames = new Set<string>();
  for (const slug of [...schema.globals, ...schema.collections]) {
    emitSlug(slug, lines, seenAuxNames, options);
    lines.push('');
  }

  // Slug → type maps.
  if (schema.globals.length > 0) {
    lines.push('export type PayloadGlobals = {');
    for (const g of schema.globals) {
      lines.push(`  '${g.slug}': ${g.typeName};`);
    }
    lines.push('};');
    lines.push('');
  }
  if (schema.collections.length > 0) {
    lines.push('export type PayloadCollections = {');
    for (const c of schema.collections) {
      lines.push(`  '${c.slug}': ${c.typeName};`);
    }
    lines.push('};');
    lines.push('');
  }
  const slugAliases: string[] = [];
  if (schema.globals.length > 0) slugAliases.push('keyof PayloadGlobals');
  if (schema.collections.length > 0) slugAliases.push('keyof PayloadCollections');
  if (slugAliases.length > 0) {
    lines.push(`export type PayloadSlug = ${slugAliases.join(' | ')};`);
    lines.push('');
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

function emitSlug(
  slug: ExtractedSlug,
  lines: string[],
  seenAuxNames: Set<string>,
  options: EmitOptions,
): void {
  emitAuxiliaries(slug.typeName, slug.fields, lines, seenAuxNames, options);
  lines.push(`export interface ${slug.typeName} {`);
  for (const field of slug.fields) {
    emitFieldMember(field, slug.typeName, lines, options);
  }
  lines.push('}');
}

function emitAuxiliaries(
  prefix: string,
  fields: readonly ExtractedField[],
  lines: string[],
  seenAuxNames: Set<string>,
  options: EmitOptions,
): void {
  for (const field of fields) {
    const auxName = nestedTypeName(prefix, field.name);
    if (field.kind === 'array' || field.kind === 'group') {
      if (seenAuxNames.has(auxName)) continue;
      seenAuxNames.add(auxName);
      emitAuxiliaries(auxName, field.fields, lines, seenAuxNames, options);
      lines.push(`export interface ${auxName} {`);
      for (const inner of field.fields) {
        emitFieldMember(inner, auxName, lines, options);
      }
      lines.push('}');
      lines.push('');
    } else if (field.kind === 'blocks') {
      for (const block of field.blocks) {
        const blockTypeName = nestedTypeName(auxName, block.typeName);
        if (seenAuxNames.has(blockTypeName)) continue;
        seenAuxNames.add(blockTypeName);
        emitAuxiliaries(blockTypeName, block.fields, lines, seenAuxNames, options);
        emitBlockInterface(blockTypeName, block, lines, options);
      }
    }
  }
}

function emitBlockInterface(
  typeName: string,
  block: ExtractedBlock,
  lines: string[],
  options: EmitOptions,
): void {
  lines.push(`export interface ${typeName} {`);
  lines.push(`  blockType: '${block.slug}';`);
  for (const field of block.fields) {
    emitFieldMember(field, typeName, lines, options);
  }
  lines.push('}');
  lines.push('');
}

function emitFieldMember(
  field: ExtractedField,
  parent: string,
  lines: string[],
  options: EmitOptions,
): void {
  if (options.markLocalizedAsDeprecated && field.localized) {
    lines.push(`  /** @localized */`);
  }
  const optional = field.required ? '' : '?';
  lines.push(`  ${field.name}${optional}: ${renderFieldType(field, parent)};`);
}

function renderFieldType(field: ExtractedField, parent: string): string {
  switch (field.kind) {
    case 'scalar':
      return field.typeRef;
    case 'array':
      return `${nestedTypeName(parent, field.name)}[]`;
    case 'blocks': {
      if (field.blocks.length === 0) return 'unknown[]';
      const variants = field.blocks
        .map((b) => nestedTypeName(nestedTypeName(parent, field.name), b.typeName))
        .join(' | ');
      return `(${variants})[]`;
    }
    case 'group':
      return nestedTypeName(parent, field.name);
    case 'relationship': {
      const targetExpr: string = Array.isArray(field.target)
        ? field.target.map((t) => `'${t}'`).join(' | ')
        : `'${field.target as string}'`;
      const base = `PayloadRelationship<${targetExpr}>`;
      return field.hasMany ? `${base}[]` : base;
    }
    case 'upload':
      return 'PayloadMedia';
    case 'json':
      return 'unknown';
    case 'select': {
      if (field.options.length === 0) return field.hasMany ? 'string[]' : 'string';
      const literal = field.options.map((o) => `'${o}'`).join(' | ');
      return field.hasMany ? `(${literal})[]` : literal;
    }
  }
}

function nestedTypeName(parent: string, child: string): string {
  return `${parent}${toPascalCase(child)}`;
}
