/**
 * Render an `ExtractedSchema` as one self-contained TypeScript file: an
 * interface per global and collection, nested interfaces for groups, arrays
 * and blocks, and the `PayloadGlobals`/`PayloadCollections`/`PayloadSlug` maps.
 */
import { toPascalCase } from '../parser/names';
import type {
  ExtractedBlock,
  ExtractedField,
  ExtractedSchema,
  ExtractedSlug,
} from '../parser/types';

export interface EmitOptions {
  /** When true, localized fields carry a `@localized` JSDoc marker. */
  readonly markLocalizedAsDeprecated?: boolean;
  /** Header text at the top of the output. */
  readonly header?: string;
}

const DEFAULT_HEADER =
  '// Auto-generated by payload-live-preview/codegen.\n' +
  '// Do not edit by hand — run `pll-codegen` to regenerate.\n' +
  '/* eslint-disable */';
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u;

function memberName(name: string): string {
  if (IDENTIFIER.test(name)) return name;
  return `'${name.replace(/\\/gu, '\\\\').replace(/'/gu, "\\'")}'`;
}

function nestedTypeName(parent: string, child: string): string {
  return `${parent}${toPascalCase(child)}`;
}

function renderFieldType(field: ExtractedField, parent: string): string {
  switch (field.kind) {
    case 'scalar':
      return field.hasMany === true ? `${field.typeRef}[]` : field.typeRef;
    case 'array':
      return `${nestedTypeName(parent, field.name)}[]`;
    case 'blocks': {
      if (field.blocks.length === 0) return 'unknown[]';
      const variants = field.blocks
        .map((block) => nestedTypeName(nestedTypeName(parent, field.name), block.typeName))
        .join(' | ');
      return `(${variants})[]`;
    }
    case 'group':
      return nestedTypeName(parent, field.name);
    case 'relationship': {
      const target =
        typeof field.target === 'string'
          ? `'${field.target}'`
          : field.target.map((slug) => `'${slug}'`).join(' | ');
      const base = `PayloadRelationship<${target}>`;
      return field.hasMany ? `${base}[]` : base;
    }
    case 'upload':
      return field.hasMany === true ? 'PayloadMedia[]' : 'PayloadMedia';
    case 'json':
      return 'unknown';
    case 'select': {
      if (field.options.length === 0) return field.hasMany ? 'string[]' : 'string';
      const literal = field.options.map((option) => `'${option}'`).join(' | ');
      return field.hasMany ? `(${literal})[]` : literal;
    }
  }
}

function emitFieldMember(
  field: ExtractedField,
  parent: string,
  lines: string[],
  options: EmitOptions,
): void {
  if (options.markLocalizedAsDeprecated === true && field.localized) {
    lines.push('  /** @localized */');
  }
  const optional = field.required ? '' : '?';
  lines.push(`  ${memberName(field.name)}${optional}: ${renderFieldType(field, parent)};`);
}

function emitBlockInterface(
  typeName: string,
  block: ExtractedBlock,
  lines: string[],
  options: EmitOptions,
): void {
  lines.push(`export interface ${typeName} {`);
  lines.push(`  blockType: '${block.slug}';`);
  for (const field of block.fields) emitFieldMember(field, typeName, lines, options);
  lines.push('}', '');
}

function emitAuxiliaries(
  prefix: string,
  fields: readonly ExtractedField[],
  lines: string[],
  seen: Set<string>,
  options: EmitOptions,
): void {
  for (const field of fields) {
    const auxName = nestedTypeName(prefix, field.name);
    if (field.kind === 'array' || field.kind === 'group') {
      if (seen.has(auxName)) continue;
      seen.add(auxName);
      emitAuxiliaries(auxName, field.fields, lines, seen, options);
      lines.push(`export interface ${auxName} {`);
      for (const inner of field.fields) emitFieldMember(inner, auxName, lines, options);
      lines.push('}', '');
    } else if (field.kind === 'blocks') {
      for (const block of field.blocks) {
        const blockTypeName = nestedTypeName(auxName, block.typeName);
        if (seen.has(blockTypeName)) continue;
        seen.add(blockTypeName);
        emitAuxiliaries(blockTypeName, block.fields, lines, seen, options);
        emitBlockInterface(blockTypeName, block, lines, options);
      }
    }
  }
}

function emitSlug(
  slug: ExtractedSlug,
  lines: string[],
  seen: Set<string>,
  options: EmitOptions,
): void {
  emitAuxiliaries(slug.typeName, slug.fields, lines, seen, options);
  lines.push(`export interface ${slug.typeName} {`);
  for (const field of slug.fields) emitFieldMember(field, slug.typeName, lines, options);
  lines.push('}');
}

function emitMap(name: string, slugs: readonly ExtractedSlug[], lines: string[]): void {
  if (slugs.length === 0) return;
  lines.push(`export type ${name} = {`);
  for (const slug of slugs) lines.push(`  '${slug.slug}': ${slug.typeName};`);
  lines.push('};', '');
}

export function emitTypes(schema: ExtractedSchema, options: EmitOptions = {}): string {
  const lines: string[] = [options.header ?? DEFAULT_HEADER, ''];
  lines.push('import type { PayloadMedia, PayloadRelationship } from "payload-live-preview";', '');
  const seen = new Set<string>();
  for (const slug of [...schema.globals, ...schema.collections]) {
    emitSlug(slug, lines, seen, options);
    lines.push('');
  }
  emitMap('PayloadGlobals', schema.globals, lines);
  emitMap('PayloadCollections', schema.collections, lines);
  const slugAliases: string[] = [];
  if (schema.globals.length > 0) slugAliases.push('keyof PayloadGlobals');
  if (schema.collections.length > 0) slugAliases.push('keyof PayloadCollections');
  if (slugAliases.length > 0) {
    lines.push(`export type PayloadSlug = ${slugAliases.join(' | ')};`, '');
  }
  return lines.join('\n').replace(/\n{3,}/gu, '\n\n');
}
