/**
 * Build-time inliner for the live preview runtime.
 *
 * Bundles `src/core/runtime.ts` with esbuild, applies a final Terser compression,
 * and writes the minified IIFE as a string literal to
 * `src/inline/runtime.generated.ts`.
 *
 * The generated file is the *single source of truth* for both the
 * inline script generator and the high-level client. They never diverge
 * because they originate from the same TypeScript module.
 *
 * The build keeps `__LIVE_PREVIEW_CONFIG__` as an external global — the inline
 * generator injects consumer overrides per invocation. The auto-start branch is
 * selected statically because this entry is built only for inline execution.
 */
import { createHash } from 'node:crypto';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { minify } from 'terser';
import { buildGeneratedAt } from './source-date-epoch';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ENTRY = resolve(ROOT, 'src/core/runtime.ts');
const OUTPUT = resolve(ROOT, 'src/inline/runtime.generated.ts');
const LOADER_ENTRY = resolve(ROOT, 'src/core/loader.ts');
const LOADER_OUTPUT = resolve(ROOT, 'src/inline/loader.generated.ts');
const FRAGMENT_ENTRY = resolve(ROOT, 'src/fragment/inline.ts');
const FRAGMENT_OUTPUT = resolve(ROOT, 'src/inline/fragment.generated.ts');

const HEADER =
  `// Auto-generated by scripts/build-runtime.ts — do not edit.\n` +
  `export interface RuntimeBuildInfo { readonly generatedAt: string; readonly size: number }\n`;

const PLACEHOLDER =
  HEADER +
  `export const RUNTIME_SOURCE: string = '';\n` +
  `export const RUNTIME_CONTENT_HASH = '';\n` +
  `export const RUNTIME_INTEGRITY = '';\n` +
  `export const RUNTIME_BUILD_INFO: RuntimeBuildInfo = { generatedAt: '', size: 0 };\n`;

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function buildRuntime(): Promise<string> {
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    write: false,
    minify: true,
    format: 'iife',
    target: 'es2020',
    platform: 'browser',
    legalComments: 'none',
    treeShaking: true,
    logLevel: 'silent',
    // The inline generator injects concrete values via `var` declarations
    // prepended to the IIFE. esbuild must therefore keep references to
    // these globals as identifiers, not literal-replace them.
    define: {
      'process.env.NODE_ENV': '"production"',
      // Statically disables the `new Function('import.meta…')` probe —
      // inline classic scripts can never have import.meta, and the
      // probe counts as eval under a strict CSP.
      __INLINE_RUNTIME_BUILD__: 'true',
      __INLINE_BUILD__: 'true',
    },
    tsconfig: resolve(ROOT, 'tsconfig.json'),
  });
  const file = result.outputFiles[0];
  if (!file) throw new Error('esbuild produced no output');
  // esbuild performs the syntax lowering and its first minification pass.
  // Terser's conservative multi-pass compressor then removes enough repeated
  // lifecycle/validation scaffolding to keep the shipped inline runtime within
  // its gzip budget without raising the ES2020 browser syntax target.
  const compressed = await minify(file.text, {
    compress: {
      passes: 3,
      // The input is a closed IIFE with no module exports. Module-aware
      // compression and declaration hoisting expose repeated lifecycle setup
      // to Terser without changing the ES2020 syntax target or public names.
      module: true,
      hoist_funs: true,
      hoist_vars: true,
      // Large sequences and aggressive inlining save raw bytes here but make
      // the highly repetitive validation/lifecycle code compress worse.
      sequences: false,
      inline: 1,
      join_vars: false,
      // Off since `inspect()` exists. The setting rewrites `true`/`false` to
      // `1`/`0`, which was safe while every literal boolean stayed internal —
      // the ready handshake was the one exception and got pinned individually
      // after F-31. A public snapshot ends that: `started` reads a slot
      // assigned from a literal and is typed `boolean`, so the shipped build
      // was handing consumers `1`. Two of the snapshot's three booleans
      // survived only because they come from computed expressions, which makes
      // every future field a coin flip. Costs 24 gzip bytes; buys a class of
      // contract violation that no type check can see.
      booleans_as_integers: false,
    },
    ecma: 2020,
    mangle: true,
    // ASCII escapes are value-preserving and improve Brotli dictionary reuse
    // for the few localized strings embedded in the classic-script artifact.
    format: { comments: false, ascii_only: true },
  });
  if (compressed.code === undefined) throw new Error('terser produced no output');
  return compressed.code;
}

/**
 * Build the static-delivery bootstrap.
 *
 * The asset URL and its integrity are per-deployment values and stay
 * *undefined* here on purpose: esbuild then emits identifier reads, and the
 * generator prepends the matching `var` declarations. Defining them as
 * build-time constants would let the minifier fold the integrity check away.
 *
 * No Terser pass: the bootstrap is a few hundred bytes and esbuild's own
 * minification is already at the floor. A second compressor would buy nothing
 * and add a second thing to reason about when the output changes.
 */
/** The fragment prelude: an IIFE whose result is the module namespace, kept as a global. */
async function buildFragmentPrelude(): Promise<string> {
  const result = await build({
    entryPoints: [FRAGMENT_ENTRY],
    bundle: true,
    write: false,
    minify: true,
    format: 'iife',
    globalName: '__LIVE_PREVIEW_FRAGMENT__',
    target: 'es2020',
    platform: 'browser',
    legalComments: 'none',
    treeShaking: true,
    logLevel: 'silent',
    define: { 'process.env.NODE_ENV': '"production"', __INLINE_RUNTIME_BUILD__: 'true' },
    tsconfig: resolve(ROOT, 'tsconfig.json'),
  });
  const file = result.outputFiles[0];
  if (!file) throw new Error('esbuild produced no fragment prelude');
  return file.text.trim();
}

async function buildLoader(): Promise<string> {
  const result = await build({
    entryPoints: [LOADER_ENTRY],
    bundle: true,
    write: false,
    minify: true,
    format: 'iife',
    target: 'es2020',
    platform: 'browser',
    legalComments: 'none',
    treeShaking: true,
    logLevel: 'silent',
    define: {
      'process.env.NODE_ENV': '"production"',
      __INLINE_RUNTIME_BUILD__: 'true',
    },
    tsconfig: resolve(ROOT, 'tsconfig.json'),
  });
  const file = result.outputFiles[0];
  if (!file) throw new Error('esbuild produced no loader output');
  return file.text.trim();
}

async function main(): Promise<void> {
  await mkdir(dirname(OUTPUT), { recursive: true });

  if (!(await exists(ENTRY))) {
    await writeFile(OUTPUT, PLACEHOLDER, 'utf8');
    console.warn('[build-runtime] core/runtime.ts not found — wrote placeholder');
    return;
  }

  const source = await buildRuntime();
  const generatedAt = buildGeneratedAt(process.env);
  const contentHash = createHash('sha256').update(source, 'utf8').digest('hex').slice(0, 16);
  const integrity = `sha384-${createHash('sha384').update(source, 'utf8').digest('base64')}`;
  const contents =
    HEADER +
    `export const RUNTIME_SOURCE: string = ${JSON.stringify(source)};\n` +
    `export const RUNTIME_CONTENT_HASH = ${JSON.stringify(contentHash)};\n` +
    `export const RUNTIME_INTEGRITY = ${JSON.stringify(integrity)};\n` +
    `export const RUNTIME_BUILD_INFO: RuntimeBuildInfo = { generatedAt: ${JSON.stringify(generatedAt)}, size: ${String(source.length)} };\n`;
  await writeFile(OUTPUT, contents, 'utf8');
  console.log(`[build-runtime] wrote ${OUTPUT} (${String(source.length)} bytes)`);

  const loader = await buildLoader();
  await writeFile(
    LOADER_OUTPUT,
    `// Auto-generated by scripts/build-runtime.ts — do not edit.\n` +
      `export const LOADER_SOURCE: string = ${JSON.stringify(loader)};\n`,
    'utf8',
  );
  console.log(`[build-runtime] wrote ${LOADER_OUTPUT} (${String(loader.length)} bytes)`);
  const prelude = await buildFragmentPrelude();
  await writeFile(
    FRAGMENT_OUTPUT,
    `// Auto-generated by scripts/build-runtime.ts — do not edit.\n` +
      `export const FRAGMENT_SOURCE = ${JSON.stringify(prelude)};\n`,
    'utf8',
  );
  console.log(`[build-runtime] wrote ${FRAGMENT_OUTPUT} (${String(prelude.length)} bytes)`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
