/**
 * Build-time inliner for the live preview runtime.
 *
 * Bundles `src/core/runtime.ts` with esbuild into a minified IIFE and
 * writes the result as a string literal to `src/inline/runtime.generated.ts`.
 *
 * The generated file is the *single source of truth* for both the
 * inline script generator and the high-level client. They never diverge
 * because they originate from the same TypeScript module.
 *
 * The build keeps `__LIVE_PREVIEW_CONFIG__` and `__INLINE_BUILD__` as
 * external globals — the inline generator injects concrete values for
 * them per-invocation, so the same compiled runtime serves every
 * configuration variant.
 */
import { access, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ENTRY = resolve(ROOT, 'src/core/runtime.ts');
const OUTPUT = resolve(ROOT, 'src/inline/runtime.generated.ts');

const HEADER =
  `// Auto-generated by scripts/build-runtime.ts — do not edit.\n` +
  `export interface RuntimeBuildInfo { readonly generatedAt: string; readonly size: number }\n`;

const PLACEHOLDER =
  HEADER +
  `export const RUNTIME_SOURCE: string = '';\n` +
  `export const RUNTIME_BUILD_INFO: RuntimeBuildInfo = { generatedAt: '', size: 0 };\n`;

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function buildRuntime(): Promise<string> {
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    write: false,
    minify: true,
    format: 'iife',
    target: 'es2020',
    platform: 'browser',
    legalComments: 'none',
    treeShaking: true,
    logLevel: 'silent',
    // The inline generator injects concrete values via `var` declarations
    // prepended to the IIFE. esbuild must therefore keep references to
    // these globals as identifiers, not literal-replace them.
    define: {
      'process.env.NODE_ENV': '"production"',
    },
    tsconfig: resolve(ROOT, 'tsconfig.json'),
  });
  const file = result.outputFiles[0];
  if (!file) throw new Error('esbuild produced no output');
  return file.text;
}

async function main(): Promise<void> {
  await mkdir(dirname(OUTPUT), { recursive: true });

  if (!(await exists(ENTRY))) {
    await writeFile(OUTPUT, PLACEHOLDER, 'utf8');
    console.warn('[build-runtime] core/runtime.ts not found — wrote placeholder');
    return;
  }

  const source = await buildRuntime();
  const generatedAt = new Date().toISOString();
  const escaped = JSON.stringify(source);
  const contents =
    HEADER +
    `export const RUNTIME_SOURCE: string = ${escaped};\n` +
    `export const RUNTIME_BUILD_INFO: RuntimeBuildInfo = { generatedAt: ${JSON.stringify(generatedAt)}, size: ${String(source.length)} };\n`;
  await writeFile(OUTPUT, contents, 'utf8');
  console.log(`[build-runtime] wrote ${OUTPUT} (${String(source.length)} bytes)`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
